config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get 'my_portfolio', to: 'users#my_portfolio'
  get 'my_friends', to: 'users#my_friends'
  get 'search_stock', to: 'stocks#search'
  get 'search_friends', to: 'users#search'
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true

  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
      publishable_token: 
        Rails.application.credentials.iex_cloud_client[:sandbox_api_key],
      secret_token: 
        Rails.application.credentials.iex_cloud_client[:sandbox_secret_key],
      endpoint: 'https://sandbox.iexapis.com/v1')
    
    begin
      new(ticker: ticker_symbol, 
        name: client.company(ticker_symbol).company_name, 
        last_price: client.price(ticker_symbol))
      rescue => exception
        nil
      end
  end

  def self.fetch_by_ticker(ticker_symbol)
    where(ticker: ticker_symbol.first)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  MAX_TRACKABLE_STOCKS = 10
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def can_track_stock?(ticker_symbol)
    stocks.count < MAX_TRACKABLE_STOCKS && 
      !stocks.where(ticker: ticker_symbol).exists?
  end

  def tracking_limit_reached?
    stocks.count >= MAX_TRACKABLE_STOCKS
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"
  end

  def to_s
    "name: #{full_name}, email: #{email}"
  end

  def is_friends_with?(friend_email)
    friends.where(email: friend_email).exists?
  end

  def is_not_friends_with?(friend_email)
    !is_friends_with?(friend_email)
  end

  def can_add_friend?(friend_email)
    User.find_by_email(friend_email) != self
  end

  def self.search(search_string)
    search_string.strip!
    result = []
    ['email','first_name','last_name'].each do |search_field|
      result += search_in_field(search_field, search_string)
    end
    result.uniq
  end

  def self.search_in_field(field, value)
    where("#{field} like ?", "%#{value}%")
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController

  #This controller should be deleted
  def search
    if params[:email].present?
      @friend = User.find_by_email(params[:email])
      if @friend
        respond_to do |format|
          format.js { render partial: 'users/friend_result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "#{params[:email]} friend not found - try again"
          format.js { render partial: 'users/friend_result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a friend's email to search for"
        format.js { render partial: 'users/friend_result' }
      end
    end
  end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    friend = User.find_by_email(params[:email])
    @friendship = Friendship.create(user: current_user, friend: friend)
    flash[:notice] = "#{friend.full_name} was added to your friends"
    redirect_to my_friends_path
  end
 
  def destroy
    friend = User.find(params[:id])
    Friendship.where(user_id: current_user.id, friend_id: friend.id).first.delete
    flash[:notice] = "#{friend.full_name} successfully unfriended"
    redirect_to my_friends_path
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        respond_to do |format|
          format.js { render partial: 'users/result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "#{params[:stock]} not found - try again"
          format.js { render partial: 'users/result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a stock ticker symbol to search for"
        format.js { render partial: 'users/result' }
      end
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

  def create
    stock = Stock.fetch_by_ticker(params[:ticker])
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "Stock #{stock.name} was added to your portfolio"
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    UserStock.where(user_id: current_user.id, stock_id: stock.id).first.delete
    flash[:notice] = "#{stock.ticker} successfully removed from portfolio"
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @my_stocks = current_user.stocks
    @user = current_user
  end

  def my_friends
    @my_friends = current_user.friends
  end

  def search
    if params[:friend].present?
      @friends = User.search(params[:friend])
      exclude_current_user(@friends)
      if @friends && @friends.size > 0
        respond_to do |format|
          format.js { render partial: 'users/friend_result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "#{params[:friend]} not found - try again"
          format.js { render partial: 'users/friend_result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a friend's name or email to search"
        format.js { render partial: 'users/friend_result' }
      end
    end
  end

  def exclude_current_user(friends)
    friends.reject! {|friend| friend.id == current_user.id }
  end

  def show
    @user = User.find(params[:id])
    @my_stocks = @user.stocks
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friends/_list.html.erb
<div class="row">
  <div class = "col-9">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="row">Friend Name</th>
          <th scope="row">Friend email</th>
          <th scope="row">Actions</th>
        </tr>
      </thead>
      <tbody>
        <%= @my_friends.each do |friend| %>
          <tr>
            <td><%= friend.full_name %></td>
            <td><%= friend.email %></td>
            <td><%= link_to 'View profile', user_path(friend),
                    class: 'btn btn-sm btn-success' %>
                <%= link_to 'Unfriend', friendship_path(friend), method: :delete,
                            data: {confirm: "Are you sure?"},
                            class: "btn btn-sm btn-warning" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria_label="Close">
        <span area-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class = "container">
    <%= link_to 'Finance Tracker', root_path, class: 'navbar-brand bolder' %>
    <% if current_user %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item <%= 'active' if request.path == my_portfolio_path %>">
            <%= link_to "MY Portfolio", my_portfolio_path, class: 'nav-link' %>
          </li>
          <li class="nav-item <%= 'active' if request.path == my_friends_path %>"">
            <%= link_to my_friends_path, class: 'nav-link' do %>
              <%= fa_icon 'users' %> My friends
            <% end %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
              Profile
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to edit_user_registration_path, class: 'dropdown-item' do %>
                <%= fa_icon 'edit' %> Edit profile
              <% end %>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <ul class = 'navbar-nav ml-auto'>
          <li class = 'nav-item user-name'>
            <%= fa_icon 'user' %> <%= current_user.full_name %>
          </li>
          <li class = 'nav-item'>
            <%= link_to("Logout", destroy_user_session_path,
                class: "btn btn-danger logout-button", method: :delete) %>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success search-button" type="submit">Search</button>
        </form>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
    <!--  <p class="notice"><%= notice %></p>  -->
      <%= render 'layouts/messages' %>
   <!--   <p class="alert"><%= alert %></p>   -->
       <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_list.html.erb
<div class="row">
  <div class = "col-9">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="row">Ticker</th>
          <th scope="row">Name</th>
          <th scope="row">Last Price</th>
          <th scope="row">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @my_stocks.each do |stock| %>
          <tr>
            <td><%= stock.ticker %></td>
            <td><%= stock.name %></td>
            <td><%= stock.last_price %></td>
            <td><% if current_user.can_track_stock?(stock.ticker) %>
                  <%= link_to 'Add to portfolio', user_stocks_path(
                    user: current_user, ticker: stock.ticker),
                    class: "btn btn-xs btn-success", method: :post
                  %>
                <% elsif current_user.id != @user.id %>
                  <% 
                    message = 'You are already tracking '
                    if current_user.tracking_limit_reached? 
                      message += '10 stocks'
                    else
                      message += 'this stock'
                    end
                  %>
                  <span class = "badge badge-secondary"><%= message %>
                <% end %>
              <% if current_user.id == @user.id %>
                <%= link_to 'Remove', user_stock_path(stock), method: :delete,
                            data: {confirm: "Are you sure?"},
                            class: "btn btn-sm btn-warning" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/_friend_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages'%>
</div>

<% if @friends && @friends.size > 0 %>
  <div class="card card-header results-block">
    <table class = col-md-12>
      <tbody>
        <% @friends.each do |friend| %>
          <tr>
            <td><strong>Friend Name: </strong><%= friend.full_name %></td>
            <td><strong>Friend email: </strong><%= friend.email %></td>
            <td><strong>Actions:</strong><%= link_to 'View profile', user_path(friend), 
                class: "btn btn-sm btn-success ml-5" %>
              <% if current_user.can_add_friend?(friend.email) &&
                !current_user.is_friends_with?(friend.email) %>
                <%= link_to 'Add friend', friendships_path(
                      user: current_user, email: friend.email),
                      class: "btn btn-xs btn-success ml-5", method: :post
                %>
              <% else %>
                <% message = 'You are already friends' %>
                <span class = "badge badge-secondary ml-5"><%= message %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/users/_friend_result.js.erb
document.querySelector('#friend_results').innerHTML = '<%= j render 'users/friend_result.html' %>'

app/views/users/_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages'%>
</div>

<% if @stock %>
  <div class="card card-header results-block">
    <strong>Symbol: </strong><%= @stock.ticker %>
    <strong>Company Name: </strong><%= @stock.name %>
    <strong>Last Price: </strong><%= @stock.last_price %>
    <% if current_user.can_track_stock?(@stock.ticker) %>
      <%= link_to 'Add to portfolio', user_stocks_path(
                  user: current_user, ticker: @stock.ticker),
                  class: "btn btn-xs btn-success ml-5", method: :post
      %>
    <% else %>
      <% 
        message = 'You are already tracking '
        if current_user.tracking_limit_reached? 
          message += '10 stocks'
        else
          message += 'this stock'
        end
      %>
      <span class = "badge badge-secondary"><%= message %>
    <% end %>
  </div>
<% end %>

app/views/users/_result.js.erb
document.querySelector('#results').innerHTML = '<%= j render 'users/result.html' %>'

app/views/users/my_friends.html.erb
<h1>My Friends</h1>
<div class="search-area">
  <h3>Find Friends</h3>
   <%= form_tag search_friends_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :friend, params[:friend], 
          placeholder: "Friend's name or email", 
          autofocus: true,
          class: "form-control form-control-lg" 
        %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div id="friend_results">
</div>

<% if ! @my_friends.empty? %>
  <%= render 'friends/list' %>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>
<div class="search-area">
  <h3>Search Stocks</h3>
   <%= form_tag search_stock_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :stock, params[:stock], 
          placeholder: "Stock ticker symbol", 
          autofocus: true,
          class: "form-control form-control-lg" 
        %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id="results">
</div>

<% if ! @my_stocks.empty? %>
  <%= render 'stocks/list' %>
<% end %>

app/views/users/show.html.erb
<h2>User Details</h2>

<div class="card card-header results-block">
  <table class = col-md-12>
    <tbody>
      <tr>
        <td><strong>Friend Name: </strong><%= @user.full_name %></td>
        <td><strong>Friend email: </strong><%= @user.email %></td>
        <td>
          <% if current_user.can_add_friend?(@user.email) &&
            current_user.is_not_friends_with?(@user.email) %>
            <%= link_to 'Add friend', friendships_path(
                  user: current_user, email: @user.email),
                  class: "btn btn-xs btn-success ml-5", method: :post
            %>
          <% else %>
            <span class = "badge badge-primary ml-5"><%= 'You are already friends' %>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>


<% if ! @my_stocks.empty? %>
  <%= render 'stocks/list' %>
<% else %>
  <p class="lead">This user is not tracking any stocks</p>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to the finance tracker app home page</h1>
<%= link_to 'Sign out', destroy_user_session_path, method: :delete %>